config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: :show

  get 'search', to: 'users#search'

  resources :channels, except: %i[index show] do
    get '/users', to: 'participants#index', as: :participants
    post 'users/:id', to: 'participants#add', as: :add_participants
    delete '/users/:id', to: 'participants#remove', as: :remove_participants
    get 'search', to: 'participants#search'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :chats, only: %i[index show] do
    resources :messages, only: :create
  end
  # Defines the root path route ("/")
  root to: 'chats#index'
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  include ParticipantsHelper
  before_action :set_channel, :set_participants
  before_action :authorization_for_index, only: :index
  before_action :authorization_for_add_remove, :set_user, only: %i[add remove]

  def index; end

  def search
    @users = @q.result(distinct: true).where.not(id: @participants.pluck(:id)).with_attached_avatar
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  def add
    if @participants.include?(@user)
      flash.now[:notice] = 'Already a Participant'
    else
      @participants << @user
      flash.now[:success] = 'Added Successfully'
    end
  end

  def remove
    if @user == @channel.admin
      flash.now[:alert] = 'Cannot remove Admin!'
      display_flash_with_turbo_stream
      return
    end
    @participants.delete(@user)
    flash.now[:alert] = 'Removed Successfully'
  end

  private

  def set_channel
    @channel = Channel.find_by(id: params[:channel_id])
  end

  def set_user
    @user = User.find(params[:id])
  end

  # If the user is not authorized, raise exception
  def authorization_for_add_remove
    raise User::NotAuthorized unless admin?
  end

  # checks if user is participant for index action
  def authorization_for_index
    return if @channel.chat.users.include?(current_user)

    raise User::NotAuthorized
  end

  def set_participants
    @participants = @channel.chat.users
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
  # check for super admin or group admin
  def admin?
    current_user.is_admin || (current_user == @channel.admin)
  end
end

app/views/participants/_participants.html.erb
<%= turbo_frame_tag user do %>
  <div class="search-results-each participants-each">
    <%= image_tag(user.avatar.variant(:small), alt: "User Avatar", class: "search-results-each-avatar") if user.avatar.attached? %>
    <h3><%= user.name %></h3>
    <h4><%= user.email %></h4>
    <% if admin? and @channel.admin!=user%>
      <%= button_to channel_remove_participants_path(@channel,user),method: :delete,class: "delete-btn" do %><i class="fa-solid fa-trash-can"></i><% end %>
    <% end %>
  </div>
<% end %>

app/views/participants/_search_form.html.erb
<%= turbo_frame_tag "search-form right",class: 'search-form right' do %>
  <%= search_form_for @q, url: channel_search_path , data:{turbo_frame: "search-results right", controller: "form"} do |f| %>
    <input type="hidden" name="format" value="turbo_stream">
    <div class="right-inner-addon ">
      <%= f.search_field :name_or_email_cont, class: 'search-input', placeholder: 'Search', autocomplete: "off",data:{action: "input->form#submit"} %>
      <i class="fa-solid fa-magnifying-glass"></i>
    </div>
  <% end %>
<% end %>

app/views/participants/_search_results.html.erb
    <%=turbo_frame_tag user do %>
    <div class="search-results-each">
        <%= image_tag(user.avatar.variant(:small), alt: "User Avatar", class: "search-results-each-avatar") if user.avatar.attached? %>
        <h3><%= user.name %></h3>
        <h4><%= user.email %></h4>
        <%= button_to channel_add_participants_path(channel,user), class: "add-participants-btn", method: :post do%><i class="fa-solid fa-plus"></i><% end %>
    </div>
    <% end %>

app/views/participants/add.turbo_stream.erb
<%= turbo_stream.remove @user %>
<%= turbo_stream.append "participants", partial: "participants", locals: {user: @user}%>
<%= turbo_stream.prepend('flash', partial: 'shared/flash') %>

app/views/participants/index.html.erb
<%= turbo_frame_tag "right-panel" do%>
  <%= link_to @channel.chat, class: "back-arrow" do %><i class="fa-solid fa-arrow-left"></i><% end %>
  <h2 class="participants-title">Participants</h2>
  <%=turbo_frame_tag "participants" do %>
      <% @participants.each do |participant| %>
        <%= render partial: "participants", locals:{user: participant, channel: @channel} %>
      <% end %>
  <% end %>
  <% if admin? %>
  <div class="search">
    <h2 class="participants-add">
      Add Participants 
    <h2>
    <%= render partial: "participants/search_form" %>
  </div>
  
  <div class="search-results right ">
  <%= turbo_frame_tag "search-results-right",class: "search-results-frame"%>
  </div>
  <% end %>
<% end %>

app/views/participants/remove.turbo_stream.erb
<%= turbo_stream.remove @user %>
<%=turbo_stream.prepend('flash', partial: 'shared/flash')%>

app/views/participants/search.turbo_stream.erb
<%= turbo_stream.update "search-results-right" do%>
    <h3>Users</h3>
    <% @users.each do |user|%>
        <%= render partial: "search_results", locals: {user: user, channel: @channel}  %>
    <% end %>
<% end %>