config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: :show

  get 'search', to: 'users#search'

  resources :channels, except: %i[index show] do
    get '/users', to: 'participants#index', as: :participants
    post 'users/:id', to: 'participants#add', as: :add_participants
    delete '/users/:id', to: 'participants#remove', as: :remove_participants
    get 'search', to: 'participants#search'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :chats, only: %i[index show] do
    resources :messages, only: :create
  end
  # Defines the root path route ("/")
  root to: 'chats#index'
end

app/models/user.rb
class User < ApplicationRecord
  # default_scope { includes(avatar_attachment: :blob) }

  enum gender: { male: 0, female: 1, other: 2 }

  # association macros
  has_many :user_chats, dependent: :destroy
  has_many :chats, through: :user_chats

  has_many :channels, -> { includes(:chat) }, through: :chats
  has_one_attached :avatar, dependent: :destroy do |attachable|
    attachable.variant :thumb, resize_to_limit: [120, 150]
    attachable.variant :small, resize_to_limit: [60, 60]
  end

  # scopes
  scope :except_current_user, ->(user) { where.not(id: user.id) }

  # validations macros
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, if: :domain_is_ok
  validates :name, presence: true, format: { with: /\A[a-zA-Z ]+\z/, message: 'only allows letters and spaces' }
  validates :gender, presence: true, inclusion: { in: User.genders.keys }

  # callbacks
  before_validation :squish_name_and_email_spaces
  after_commit :add_default_avatar, on: :update

  # devise
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # method to retrieve inboxes
  def self.inboxes(current_user)
    current_user.chats.private_chats.includes({ users: { avatar_attachment: :blob } },
                                              :last_message)
                .filter_current_user(current_user).where.not(last_message_id: nil)
  end

  # methods for ransack gem
  def self.ransackable_attributes(_auth_object = nil)
    %w[name email]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end

  # to raise exception related to authorization
  class NotAuthorized < StandardError
  end

  private

  # method to check subdomain of registering user
  def domain_is_ok
    return if Rails.application.config.approved_domains.any? { |word| email.end_with?(word) }

    errors.add(:email, 'is not from a valid domain')
  end

  # method to strip white spaces at ends and any extras in between
  def squish_name_and_email_spaces
    [name, email].each { |attr| attr.squish! if attr.present? }
  end

  # method to load default avatar
  def add_default_avatar
    return if avatar.attached?

    avatar.attach(
      io: File.open(Rails.root.join('app', 'assets', 'images', 'default_avatar.jpg')),
      filename: 'default_avatar.jpg',
      content_type: 'image/jpg'
    )
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def search
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).except_current_user(current_user).with_attached_avatar.includes(:chats)
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  def show
    set_recepient
    if @recepient == current_user
      flash[:notice] = 'This is You!'
      redirect_to chats_path
    else
      set_private_chat_if_exists_else_create
      redirect_to chat_path(@chat), status: :see_other
    end
  end

  private

  # set recepient for private chat to show their info
  def set_recepient
    @recepient = User.find_by(id: params[:id])
  end

  # finds private chat if already exist between users else create
  def set_private_chat_if_exists_else_create
    @chat = Chat.private_chat_between(current_user, @recepient).first || Chat.create(users: [@recepient, current_user])
  end
end

app/views/users/_search_form.html.erb
<%= turbo_frame_tag "search-form",class: 'search-form' do %>
  <%= search_form_for @q, url: search_path , data:{turbo_frame: "search-results", controller: "form"} do |f| %>
    <input type="hidden" name="format" value="turbo_stream">
    <div class="right-inner-addon ">
      <%= f.search_field :name_or_email_cont, class: 'search-input', placeholder: 'Search', autocomplete: "off",data:{action: "input->form#submit"} %>
      <i class="fa-solid fa-magnifying-glass"></i>
    </div>
  <% end %>
<% end %>

app/views/users/_search_results.erb
<%= link_to user_path(user), data: {turbo_frame: "central-and-right-panels"} do %>
  <div class="search-results-each">
    <%= image_tag(user.avatar.variant(:small), alt: "User Avatar", class: "search-results-each-avatar") if user.avatar.attached? %>
    <h3><%= user.name %></h3>
    <h4><%= user.email %></h4>
  </div>
<% end %>

app/views/users/search.html.erb
<%= turbo_frame_tag "search-results" do %>
  <h3>Users</h3>
  <%= render partial: "search_results", collection: @users, as: :user %>
<% end %>

app/views/users/search.turbo_stream.erb
<%= turbo_stream.update "inboxes", "" %>

<%= turbo_stream.update "search-results" do%>
  <h3>Users</h3>
  <%= render partial: "search_results", collection: @users, as: :user  %>
<% end %>