config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: :show

  get 'search', to: 'users#search'

  resources :channels, except: %i[index show] do
    get '/users', to: 'participants#index', as: :participants
    post 'users/:id', to: 'participants#add', as: :add_participants
    delete '/users/:id', to: 'participants#remove', as: :remove_participants
    get 'search', to: 'participants#search'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :chats, only: %i[index show] do
    resources :messages, only: :create
  end
  # Defines the root path route ("/")
  root to: 'chats#index'
end

app/models/chat.rb
class Chat < ApplicationRecord
  default_scope { order(updated_at: :desc) }

  has_many :user_chats, dependent: :destroy
  has_many :users, through: :user_chats

  has_many :messages, dependent: :destroy
  belongs_to :last_message, class_name: 'Message', optional: true

  has_one :channel, touch: true, dependent: :destroy

  scope :channels, -> { where(is_channel: true) }
  scope :private_chats, -> { where(is_channel: false) }
  scope :filter_current_user, ->(current_user) { where.not(users: { id: current_user }) }

  def self.messages_with_image_and_sender_avatar_included(chat)
    chat.messages.with_attached_image.includes(sender: { avatar_attachment: :blob })
  end

  # method to check if private chat exists between users
  def self.private_chat_between(current_user, user)
    return if current_user == user

    current_user.chats.private_chats.joins(:users).where(users: { id: user })
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  layout 'homepage'
  before_action :set_chat, :authenticate_if_user_belongs_to_chat!, only: :show

  def index
    @channels = current_user.channels
    @q = User.ransack(params[:q])
    @inboxes = User.inboxes(current_user)
  end

  def show
    set_recepient_info unless @chat.is_channel
    @messages = Chat.messages_with_image_and_sender_avatar_included(@chat)
  end

  private

  def set_chat
    @chat = Chat.find_by(id: params[:id])
  end

  # to show recepient info for private chat in right panel
  def set_recepient_info
    @recepient = @chat.users.except_current_user(current_user).with_attached_avatar.first
  end

  # to prevent unauthorized user from others chat
  def authenticate_if_user_belongs_to_chat!
    raise User::NotAuthorized unless @chat.users.include?(current_user)
  end
end

app/views/chats/_channel.html.erb
<%= link_to chat_path(channel.chat), data: {turbo_frame: "central-and-right-panels" } do %>
<div id="<%= dom_id channel %>" class="channels-each">
    <div class="channel-logo"><%= channel.name[0] %></div>
    <div class="channel-name"><%= channel.name %></div>  
</div>
<% end %>

app/views/chats/_inbox.html.erb
<%= link_to chat_path(inbox), data: {turbo_frame: "central-and-right-panels"} do %>
<div class="inboxes-each" id= <%=dom_id(inbox)%> >
    <%= image_tag(inbox.users[0].avatar.variant(:small), alt: "User Avatar", class: "inboxes-each-avatar") if inbox.users[0].avatar.attached? %>
    <h3><%=inbox.users[0].name%></h3><br>
    <h4><%=inbox.last_message.present? ? inbox.last_message.content : ""%></h4>
</div>
<% end %>

app/views/chats/index.html.erb
<div class="homepage-box">

  <div class="homepage-left-panel">
    <div class="user-card">
      <h1>Chat</h1>
        <%= image_tag(current_user.avatar.variant(:thumb), alt: "User Avatar") if current_user.avatar.attached? %>
        <h2><%=current_user.name%></h2> 
        <p>Active</p>
    </div>

    <div class="homepage-left-panel-below">
      <%= turbo_frame_tag "refresh-left-panel" do%>
        <div class="channels-box">
          <h2>
            Channels
            <%=link_to image_tag("add_button", class: "btn-create"), new_channel_path, data: {turbo_frame: "central-and-right-panels"} %>
          </h2>
          <%= turbo_frame_tag "channels" do%>
          <div class="channels">
            <%= @channels.any? ? render(partial: "channel", collection: @channels) : "<p class='no-groups'>No Groups</p>".html_safe %>
          </div>
          <% end %>
        </div>
        <%= turbo_frame_tag "empty-search-results" do%>
          <div class="search">
            <h2>
              Search 
            <h2>
            <%= render partial: "users/search_form" %>
          </div>
          <div class="search-results">
          <%= turbo_frame_tag "search-results",class: "search-results-frame"%>
            </div>

            
          <%=turbo_frame_tag "inboxes", class: "inboxes" do %>
              <h2>Chats</h2>
              <%= render partial: "inbox", collection: @inboxes %>
          <%end%>
        <% end %>
      <% end %>
    </div>
  </div>

    <%= turbo_frame_tag "central-and-right-panels", class: "homepage-central-and-right-panels" do %>
      <div class="no-conversations"> No Conversations </div> 

    <% end %>
</div>

app/views/chats/show.html.erb
<%= turbo_frame_tag "central-and-right-panels", class: "homepage-central-and-right-panels"  do %>
  <div id="flash" class="flash">
    <%= render "shared/flash" %>
  </div>

  <div class="homepage-central-panel">
    <%= turbo_frame_tag "central-panel" do%>
    
      <%= turbo_stream_from @chat, "messages" %> 

      <%= turbo_frame_tag "chats-show", class: "chats-show" do%>
        <% if @messages.present? %>  
            <%= render partial:"messages/message_box", collection: @messages, as: :message %>
        <% end %>
      <% end %>

      <%= turbo_frame_tag "messages-new", class: "messages-new" do%>
        <%= render partial:"messages/new_message_form" ,locals: { chat: @chat, message: @chat.messages.build } %>
      <% end %>
     <% end %> 
  </div>
 
  <div class="homepage-right-panel">
    <%= turbo_frame_tag "right-panel" do%>

      <% if @chat.is_channel? %>
        <div class="right-channel-card">
          <%if current_user==@chat.channel.admin%>
            <%= link_to channel_path(@chat.channel), data: {turbo_method: :delete,turbo_frame: "_top", confirm: 'Are you sure?' },class: "delete-channel" do%>
              <i class="fa-solid fa-trash-can"></i>
            <% end %>
          <% end %>
          <div class="channel-logo"><%= @chat.channel.name[0] %></div>
          <h2><%= @chat.channel.name %><h2> 
          <h3><%= (current_user==@chat.channel.admin) ? "Channel Admin" : "Channel Member"%></h3>
          <%= link_to image_tag("Setting.png", alt: "Settings Logo"), edit_channel_path(@chat.channel), data: {turbo_frame: "central-panel" }%>
        </div>
        <div class="show-participants">
        <%= image_tag("users", alt: "Participants", class: "participants-icon") %>
        <%= link_to "Participants", channel_participants_path(@chat.channel), class: "participants-show-link"%>
      </div> 
      <% else %>
        <div class="user-card recepient-card">
          <%= image_tag(@recepient.avatar.variant(:thumb), alt: "Recepient Avatar") if @recepient.avatar.attached? %>
          <h2><%=@recepient.name%></h2> 
        </div>
      <% end %> 
    <% end%> 
  </div>
<% end %>