config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: :show

  get 'search', to: 'users#search'

  resources :channels, except: %i[index show] do
    get '/users', to: 'participants#index', as: :participants
    post 'users/:id', to: 'participants#add', as: :add_participants
    delete '/users/:id', to: 'participants#remove', as: :remove_participants
    get 'search', to: 'participants#search'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :chats, only: %i[index show] do
    resources :messages, only: :create
  end
  # Defines the root path route ("/")
  root to: 'chats#index'
end

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <%= link_to root_path do %>
  <div class="logo-first">
      biz
  </div>
  <% end %>
  <div class="sidebar-buttons">
    <%= link_to edit_user_registration_path,   data: { turbo_frame: "central-and-right-panels" } do %>
    <i class="fa-solid fa-wrench fa-2xl"></i>
    <% end %>
    <%= link_to chats_path, data: {turbo_frame: "refresh-left-panel"} do %>
    <i class="fa-regular fa-comment fa-2xl"></i>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BizChatAnish</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BizChatAnish</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style> .send-by-<%=current_user.id%> {align-self: end; flex-direction: row-reverse}
            .send-by-<%=current_user.id%> main {align-items: flex-end}
            .send-by-<%=current_user.id%> .message-content  {color: white; background-color:rgb(179, 179, 247)  }

    </style>

  </head>

  <body>
    <%= render partial: "layouts/sidebar" %>
    <div id="flash" class="flash">
      <%= render "shared/flash" %>
    </div>
    <%= yield %>
  </body>
</html>